name: AWS ECR Login

on:
  push:
    branches:
      - 'release*'

jobs:
  ecr-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} > password.txt

      - name: Upload password.txt
        uses: actions/upload-artifact@v4
        with:
          name: ecr-password
          path: password.txt
