name: Publish Backend

on:
  push:
    branches:
      - 'release*'

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: ecr-login
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ecr-password

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and Push with Jib
        run: |
          cd backend
          ./gradlew jib -Djib.to.image=${{ secrets.AWS_ECR_REPO_URI }} -Djib.to.auth.username=AWS -Djib.to.auth.password=$(cat ../password.txt)
